// An original educational camera: a composite design, not a service manual for a specific product.
export const parts=[
['body','Camera body','بدنهٔ دوربین','The rigid housing holds the optical and electronic assemblies in alignment and protects them during production.','بدنه، مجموعه‌های اپتیکی و الکترونیکی را در جای دقیق خود نگه می‌دارد و هنگام فیلم‌برداری از آن‌ها محافظت می‌کند.','This is a generic educational design. Internal placement differs between real cameras.','این مدل آموزشی عمومی است. جای قطعات داخلی در دوربین‌های واقعی متفاوت است.'],
['lens','Lens assembly','مجموعهٔ لنز','Multiple optical elements collect light and focus an image onto the sensor. Lens design influences field of view, distortion and image character.','عدسی‌های متعدد نور را جمع می‌کنند و تصویر را روی حسگر متمرکز می‌کنند. طراحی لنز بر زاویهٔ دید، اعوجاج و ویژگی‌های تصویر اثر می‌گذارد.','Coatings reduce unwanted reflections; a real lens contains several glass elements.','پوشش‌های اپتیکی بازتاب‌های ناخواسته را کاهش می‌دهند؛ لنز واقعی شامل چند عدسی است.'],
['focus','Focus ring','حلقهٔ فوکوس','Turning the focus ring adjusts the optical focusing system so the intended subject appears sharp.','چرخاندن حلقهٔ فوکوس، سامانهٔ اپتیکی را تنظیم می‌کند تا سوژهٔ موردنظر واضح دیده شود.','On some lenses the ring moves elements mechanically; on others it sends an electronic command.','در بعضی لنزها حلقه مستقیماً عدسی‌ها را جابه‌جا می‌کند؛ در بعضی دیگر فرمان الکترونیکی می‌فرستد.'],
['zoom','Zoom ring','حلقهٔ زوم','Changes focal length by moving optical groups, making the framing wider or tighter without moving the camera.','با جابه‌جایی گروه‌های عدسی، فاصلهٔ کانونی را تغییر می‌دهد و بدون حرکت دوربین قاب را بازتر یا بسته‌تر می‌کند.','Only zoom lenses have variable focal length. A prime lens has a fixed focal length.','فقط لنزهای زوم فاصلهٔ کانونی متغیر دارند؛ فاصلهٔ کانونی لنز پرایم ثابت است.'],
['iris','Iris control','کنترل دیافراگم','Controls the aperture opening, regulating how much light passes through the lens and helping set depth of field.','اندازهٔ دهانهٔ دیافراگم را کنترل می‌کند تا مقدار نور عبوری و عمق میدان تنظیم شود.','Cinema lenses often use T-stops, which account for actual light transmission.','لنزهای سینمایی اغلب با T-stop درجه‌بندی می‌شوند که میزان واقعی عبور نور را در نظر می‌گیرد.'],
['mount','Lens mount','مانت لنز','Secures the lens to the body at a precise distance from the sensor. Some mounts also carry power and lens data.','لنز را در فاصلهٔ دقیق از حسگر به بدنه وصل می‌کند. برخی مانت‌ها برق و اطلاعات لنز را نیز منتقل می‌کنند.','Flange focal distance must be accurate for reliable focus, especially at infinity.','فاصلهٔ فلنج باید دقیق باشد تا فوکوس، به‌خصوص در بی‌نهایت، درست انجام شود.'],
['sensor','Image sensor','حسگر تصویر','Converts incoming light into electrical signals. These are read and processed to form digital images.','نور دریافتی را به سیگنال الکتریکی تبدیل می‌کند. این سیگنال‌ها خوانده و پردازش می‌شوند تا تصویر دیجیتال تشکیل شود.','Sensor size affects field of view for a given focal length. Low-light quality also depends on sensor technology.','اندازهٔ حسگر در فاصلهٔ کانونی ثابت بر زاویهٔ دید اثر دارد. کیفیت نور کم به فناوری حسگر نیز وابسته است.'],
['monitor','LCD monitor','نمایشگر LCD','Displays the live image and camera settings so the operator can check framing, exposure and focus.','تصویر زنده و تنظیمات دوربین را نشان می‌دهد تا فیلم‌بردار بتواند قاب‌بندی، نوردهی و فوکوس را بررسی کند.','Focus peaking and false color are monitoring aids; they are normally not recorded into the image.','فوکوس‌پیکینگ و رنگ کاذب ابزارهای کمکی نمایش‌اند و معمولاً در تصویر ضبط‌شده ثبت نمی‌شوند.'],
['viewfinder','Electronic viewfinder','منظره‌یاب الکترونیکی','A small enclosed display shows the live image through an eyepiece, making it easier to judge outdoors.','نمایشگر کوچک داخل محفظه، تصویر زنده را از طریق چشمی نشان می‌دهد و دیدن تصویر در فضای روشن را آسان می‌کند.','The eyecup blocks stray light. Diopter adjustment helps match the eyepiece to the operator’s eyesight.','لاستیک چشمی نور مزاحم را کم می‌کند. تنظیم دیوپتر به تطبیق چشمی با بینایی فیلم‌بردار کمک می‌کند.'],
['microphone','Microphone','میکروفون','Converts sound pressure changes into an electrical audio signal that can be recorded with the picture.','تغییرات فشار صوت را به سیگنال الکتریکی صوتی تبدیل می‌کند تا همراه تصویر ضبط شود.','An on-camera microphone is useful for reference audio; dialogue often benefits from a closer microphone.','میکروفون روی دوربین برای صدای مرجع مفید است؛ برای دیالوگ معمولاً میکروفون نزدیک‌تر نتیجهٔ بهتری دارد.'],
['handle','Top handle','دستهٔ بالایی','Provides a secure carrying point and supports low-angle handheld operation and compatible accessories.','برای حمل مطمئن، فیلم‌برداری دستی از زاویهٔ پایین و نصب لوازم سازگار استفاده می‌شود.','Always follow the rated load of the handle and its mounting hardware.','ظرفیت مجاز دسته و اتصالات آن را رعایت کنید.'],
['grip','Side grip','دستهٔ جانبی','Supports the operator’s hand for handheld shooting and can place recording controls within reach.','تکیه‌گاه دست فیلم‌بردار است و می‌تواند کنترل‌های ضبط را در دسترس قرار دهد.','A secure hand strap improves handling; it does not replace a properly balanced rig.','بند محکم، کنترل دوربین را بهتر می‌کند؛ اما جای تجهیزات متعادل را نمی‌گیرد.'],
['record','Record button','دکمهٔ ضبط','Starts or stops recording when the camera has compatible media, power and valid recording settings.','در صورت وجود حافظهٔ سازگار، برق و تنظیمات معتبر، ضبط را شروع یا متوقف می‌کند.','Always check the recording indicator and remaining media time after pressing record.','پس از زدن دکمه، نشانگر ضبط و زمان باقی‌ماندهٔ حافظه را بررسی کنید.'],
['dial','Control dial','پیچ تنظیم','Changes a selected setting or navigates menus. Its assignment depends on the camera and operating mode.','تنظیم انتخاب‌شده را تغییر می‌دهد یا در منوها جابه‌جا می‌شود. وظیفهٔ آن به مدل دوربین و حالت کار بستگی دارد.','Exposure controls include shutter, aperture and gain or ISO; their effects are different.','شاتر، دیافراگم و گین یا ISO از کنترل‌های نوردهی‌اند و اثرهای متفاوتی دارند.'],
['battery','Battery','باتری','Supplies electrical power to the camera and, where supported, attached accessories.','برق دوربین و در صورت پشتیبانی، لوازم جانبی متصل را تأمین می‌کند.','Watt-hours describe stored energy. Approximate runtime is watt-hours divided by power draw in watts.','وات‌ساعت میزان انرژی ذخیره‌شده است. زمان کار تقریبی از تقسیم وات‌ساعت بر مصرف وات به دست می‌آید.'],
['batteryMount','Battery plate','صفحهٔ اتصال باتری','Mechanically locks the battery onto the camera and connects its power contacts.','باتری را روی دوربین قفل می‌کند و اتصال الکتریکی آن را برقرار می‌سازد.','Battery format, voltage and current capability must be compatible with the camera.','نوع باتری، ولتاژ و توان جریان‌دهی باید با دوربین سازگار باشند.'],
['memory','Media slot','درگاه کارت حافظه','Holds removable recording media for video, audio and metadata. A protective door keeps the media secure.','رسانهٔ ضبط قابل‌حمل را برای ذخیرهٔ تصویر، صدا و فراداده در خود جای می‌دهد. درپوش از کارت محافظت می‌کند.','Sustained write speed matters. Use media approved for the selected codec and recording rate.','سرعت نوشتن پایدار مهم است. از حافظهٔ تأییدشده برای کدک و نرخ ضبط انتخابی استفاده کنید.'],
['sdi','SDI output','خروجی SDI','Sends a digital video signal through a locking BNC connector to compatible monitors, recorders or production equipment.','سیگنال ویدیوی دیجیتال را از اتصال قفل‌شوندهٔ BNC به نمایشگر، رکوردر یا تجهیزات سازگار می‌فرستد.','Supported resolution and frame rate depend on the SDI standard implemented by the camera.','وضوح و نرخ فریم پشتیبانی‌شده به استاندارد SDI دوربین بستگی دارد.'],
['hdmi','HDMI output','خروجی HDMI','Carries digital video and audio to compatible displays or recorders. Available output modes depend on the camera.','تصویر و صدای دیجیتال را به نمایشگر یا رکوردر سازگار منتقل می‌کند. حالت‌های خروجی به دوربین وابسته‌اند.','Use cable strain relief on a rig to reduce stress on the connector.','برای کاهش فشار روی سوکت، کابل را روی ریگ مهار کنید.'],
['usb','USB / data port','درگاه USB و داده','Provides a connection for supported functions such as data transfer, camera control or firmware updates.','برای قابلیت‌های پشتیبانی‌شده مانند انتقال داده، کنترل دوربین یا به‌روزرسانی میان‌افزار اتصال فراهم می‌کند.','USB connector shape alone does not tell you its data speed or whether charging is supported.','شکل سوکت USB به‌تنهایی سرعت انتقال یا پشتیبانی از شارژ را مشخص نمی‌کند.'],
['audio','XLR audio input','ورودی صدای XLR','Accepts a balanced audio signal from a compatible microphone or audio source. Input level is selected to match the source.','سیگنال صدای بالانس را از میکروفون یا منبع سازگار دریافت می‌کند. سطح ورودی باید با منبع هماهنگ باشد.','Some microphones need 48 V phantom power. Enable it only when appropriate for the connected equipment.','برخی میکروفون‌ها به فانتوم‌پاور ۴۸ ولت نیاز دارند. آن را متناسب با تجهیزات متصل فعال کنید.'],
['vent','Cooling system','سامانهٔ خنک‌کننده','Vents, heatsinks and fans move heat away from electronics to help maintain a stable operating temperature.','دریچه‌ها، هیت‌سینک و فن گرما را از مدارها دور می‌کنند تا دمای کار پایدار بماند.','Keep vents unobstructed. Cooling design also aims to limit noise during sound recording.','دریچه‌ها را مسدود نکنید. در طراحی خنک‌کننده، کاهش صدای مزاحم ضبط نیز اهمیت دارد.'],
['tripod','Tripod baseplate','صفحهٔ اتصال سه‌پایه','Attaches the camera to a support system and can hold rods for lens supports and other rig accessories.','دوربین را به سامانهٔ نگهدارنده وصل می‌کند و می‌تواند میله‌های تکیه‌گاه لنز و سایر تجهیزات ریگ را نگه دارد.','Use the correct screw length and balance the camera on the head before shooting.','از پیچ با طول مناسب استفاده کنید و پیش از فیلم‌برداری دوربین را روی هد متعادل کنید.'],
['shoe','Accessory mount','محل نصب لوازم جانبی','Provides a mechanical attachment point for compatible accessories such as lights, receivers or monitor brackets.','نقطهٔ اتصال مکانیکی برای لوازم سازگار مانند چراغ، گیرنده یا پایهٔ نمایشگر است.','A cold shoe is mechanical only; a hot shoe also includes electrical contacts.','کفشک سرد فقط اتصال مکانیکی دارد؛ کفشک گرم کنتاکت‌های الکتریکی هم دارد.']
].map((p,i)=>({id:p[0],index:i+1,en:{title:p[1],description:p[3],note:p[5]},fa:{title:p[2],description:p[4],note:p[6]}}));
export const ui={en:{subtitle:'Interactive Camera Anatomy',exhibit:'EXHIBIT 01 / CINEMA TECHNOLOGY',title:'A closer look.',intro:'Explore the craft behind the image.',side:'THE ANATOMY OF AN IMAGE',note:'TECHNICAL NOTE',next:'Next component →',model:'Modular cinema camera · Educational model',parts:'Explore components',gesture:'DRAG TO ROTATE · SCROLL TO ZOOM · CLICK TO EXPLORE',reset:'Reset view',rotate:'Auto rotate',footer:'EXPLORE. INSPECT. UNDERSTAND.',explode:'Explode camera',assemble:'Assemble camera'},fa:{subtitle:'شناخت تعاملی اجزای دوربین',exhibit:'نمایشگاه ۰۱ / فناوری سینما',title:'نگاهی نزدیک‌تر.',intro:'هنر و فناوری پشت تصویر را کشف کنید.',side:'کالبدشناسی یک تصویر',note:'نکتهٔ فنی',next:'قطعهٔ بعدی ←',model:'دوربین سینمایی ماژولار · مدل آموزشی',parts:'بررسی اجزای دوربین',gesture:'کشیدن برای چرخش · زوم با دو انگشت یا اسکرول · لمس برای بررسی',reset:'بازنشانی نما',rotate:'چرخش خودکار',footer:'کاوش. بررسی. یادگیری.',explode:'باز کردن اجزای دوربین',assemble:'بستن اجزای دوربین'}};
