import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {createCamera} from './model.js';
import {parts,ui} from './content.js';
const $=id=>document.getElementById(id);let lang='en',exploded=false,selected=null,hovered=null,progress=0,targetProgress=0,focusMotion=null,ready=false;
const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
let renderer;
try{renderer=new THREE.WebGLRenderer({canvas:$('scene'),antialias:true,powerPreference:'high-performance'});}catch(e){$('loading').hidden=true;$('error').hidden=false;throw e}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.setClearColor('#131516');renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.38;
const scene=new THREE.Scene();scene.fog=new THREE.Fog('#131516',20,45);
const camera=new THREE.PerspectiveCamera(34,1,.05,100);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.07;controls.enablePan=false;controls.minDistance=4;controls.maxDistance=23;controls.maxPolarAngle=Math.PI*.84;controls.autoRotateSpeed=.24;
const pmrem=new THREE.PMREMGenerator(renderer);const environment=pmrem.fromScene(new RoomEnvironment(),.04);scene.environment=environment.texture;scene.environmentIntensity=.8;pmrem.dispose();
scene.add(new THREE.HemisphereLight('#d4e0ef','#414044',1.9));
function light(color,intensity,pos){let l=new THREE.DirectionalLight(color,intensity);l.position.set(...pos);scene.add(l);return l}
const key=light('#e9edff',4,[4,7,5]);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-7;key.shadow.camera.right=7;key.shadow.camera.top=7;key.shadow.camera.bottom=-7;key.shadow.normalBias=.035;key.shadow.bias=-.0002;light('#d0aa77',2.5,[-4,3,-3]);light('#abbecf',2.3,[0,2,-5]);
$('progress').value=40;$('loadText').textContent='Building the camera assemblies';
const {root,groups}=createCamera();scene.add(root);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.MeshStandardMaterial({color:'#171b1e',roughness:.9,metalness:.13}));floor.rotation.x=-Math.PI/2;floor.position.y=-2.28;floor.receiveShadow=true;scene.add(floor);
const shadowCanvas=document.createElement('canvas');shadowCanvas.width=shadowCanvas.height=128;const cx=shadowCanvas.getContext('2d');let gr=cx.createRadialGradient(64,64,2,64,64,64);gr.addColorStop(0,'rgba(0,0,0,.45)');gr.addColorStop(1,'rgba(0,0,0,0)');cx.fillStyle=gr;cx.fillRect(0,0,128,128);let contact=new THREE.Mesh(new THREE.PlaneGeometry(8,7),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(shadowCanvas),transparent:true,depthWrite:false}));contact.rotation.x=-Math.PI/2;contact.position.y=-2.269;scene.add(contact);
let meshes=[];root.traverse(o=>{if(o.isMesh){meshes.push(o);o.userData.originalMaterial=o.material;o.userData.highlight=null;}});
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),v=new THREE.Vector3();
function framing(){let mobile=innerWidth<700;let aspect=camera.aspect;let distance=exploded?13.2:9.0;if(mobile)distance*=Math.max(1.35,1/aspect*.95);return {pos:new THREE.Vector3(.69,.35,1).normalize().multiplyScalar(distance).add(new THREE.Vector3(0,.12,.25)),target:new THREE.Vector3(0,.12,.25)}}
function fit(animate=true){const f=framing();if(!animate||reduce){camera.position.copy(f.pos);controls.target.copy(f.target);controls.update();}else focusMotion={from:camera.position.clone(),to:f.pos,fromTarget:controls.target.clone(),toTarget:f.target,start:performance.now(),duration:1100};}
function resize(){const r=$('viewport').getBoundingClientRect();camera.aspect=r.width/r.height;camera.updateProjectionMatrix();renderer.setSize(r.width,r.height,false);controls.maxDistance=innerWidth<700?38:23;fit(false)}resize();new ResizeObserver(resize).observe($('viewport'));
function pause(){controls.autoRotate=false;$('rotate').setAttribute('aria-pressed','false')}
controls.addEventListener('start',()=>{pause();focusMotion=null});
function colorize(){for(const m of meshes){let active=m.userData.component===selected||m.userData.component===hovered;if(active){if(!m.userData.highlight){let h=m.userData.originalMaterial.clone();if(h.emissive){h.emissive.set('#a88b60');h.emissiveIntensity=.16;}m.userData.highlight=h}m.material=m.userData.highlight}else m.material=m.userData.originalMaterial}}
function hit(e){const rect=$('scene').getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);return raycaster.intersectObjects(meshes,false).find(h=>h.object.userData.component)?.object.userData.component||null}
function renderPanel(){if(!selected)return;const p=parts.find(p=>p.id===selected);$('part-index').textContent=lang==='en'?`COMPONENT ${String(p.index).padStart(2,'0')} / 24`:`قطعهٔ ${p.index.toLocaleString('fa-IR')} از ۲۴`;$('part-title').textContent=p[lang].title;$('part-description').textContent=p[lang].description;$('part-note').textContent=p[lang].note;}
function select(id,focus=true){selected=id;pause();$('panel').hidden=false;$('parts-list').hidden=true;$('parts-toggle').setAttribute('aria-expanded','false');renderPanel();colorize();if(focus&&innerWidth>=700){const pt=groups[id].getWorldPosition(new THREE.Vector3());let dir=camera.position.clone().sub(controls.target).normalize();let distance=Math.max(exploded?7:5.5,camera.position.distanceTo(controls.target)*.87);const to=pt.clone().addScaledVector(dir,distance);focusMotion={from:camera.position.clone(),to,fromTarget:controls.target.clone(),toTarget:pt,start:performance.now(),duration:reduce?0:1000}}}
function close(){selected=null;hovered=null;$('panel').hidden=true;colorize()}
$('close').onclick=close;addEventListener('keydown',e=>{if(e.key==='Escape'){close();$('parts-list').hidden=true;$('parts-toggle').setAttribute('aria-expanded','false')}});
$('next').onclick=()=>{let index=parts.findIndex(p=>p.id===selected);select(parts[(index+1)%parts.length].id)};
let down=null;const touches=new Set();let multitouch=false;
$('scene').addEventListener('pointerdown',e=>{touches.add(e.pointerId);if(touches.size>1)multitouch=true;down={x:e.clientX,y:e.clientY,time:performance.now()};pause()});
$('scene').addEventListener('pointerup',e=>{touches.delete(e.pointerId);if(!multitouch&&down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)<7&&performance.now()-down.time<700){const id=hit(e);if(id)select(id)}if(!touches.size)multitouch=false;down=null});
$('scene').addEventListener('pointercancel',e=>{touches.delete(e.pointerId);down=null;if(!touches.size)multitouch=false});
$('scene').addEventListener('pointermove',e=>{if(e.pointerType==='touch'||e.buttons)return;let id=hit(e);if(id!==hovered){hovered=id;$('scene').style.cursor=id?'pointer':'grab';colorize()}});$('scene').addEventListener('pointerleave',()=>{hovered=null;colorize()});$('scene').addEventListener('wheel',pause,{passive:true});
const labels={};const labelIds=['lens','sensor','monitor','battery','microphone','handle'];for(const id of labelIds){const el=document.createElement('button');el.className='label';el.onclick=()=>select(id);el.hidden=true;$('labels').appendChild(el);labels[id]=el;}
function language(newLang){lang=newLang;document.documentElement.lang=lang;document.documentElement.dir=lang==='fa'?'rtl':'ltr';for(const el of document.querySelectorAll('[data-i]'))el.textContent=ui[lang][el.dataset.i];$('en').setAttribute('aria-pressed',String(lang==='en'));$('fa').setAttribute('aria-pressed',String(lang==='fa'));$('explode-text').textContent=ui[lang][exploded?'assemble':'explode'];$('parts-list').replaceChildren();for(const p of parts){let b=document.createElement('button');let n=document.createElement('span');n.textContent=String(p.index).padStart(2,'0');b.append(n,document.createTextNode(p[lang].title));b.onclick=()=>select(p.id);$('parts-list').appendChild(b)}for(const id of labelIds)labels[id].textContent=parts.find(p=>p.id===id)[lang].title;renderPanel();try{localStorage.setItem('camera-lang',lang)}catch{}}
$('en').onclick=()=>language('en');$('fa').onclick=()=>language('fa');let saved='en';try{saved=localStorage.getItem('camera-lang')||'en'}catch{}language(saved==='fa'?'fa':'en');
$('parts-toggle').onclick=()=>{let show=$('parts-list').hidden;$('parts-list').hidden=!show;$('parts-toggle').setAttribute('aria-expanded',String(show))};
$('explode').onclick=()=>{exploded=!exploded;targetProgress=exploded?1:0;pause();close();$('explode-text').textContent=ui[lang][exploded?'assemble':'explode'];$('explode').setAttribute('aria-pressed',String(exploded));fit()};
$('reset').onclick=()=>{close();pause();fit()};$('rotate').onclick=()=>{controls.autoRotate=!controls.autoRotate;$('rotate').setAttribute('aria-pressed',String(controls.autoRotate));focusMotion=null};
let last=performance.now();function frame(t){const dt=Math.min((t-last)/1000,.05);last=t;
 if(progress!==targetProgress){progress=reduce?targetProgress:THREE.MathUtils.damp(progress,targetProgress,4.3,dt);if(Math.abs(progress-targetProgress)<.00015)progress=targetProgress;const eased=progress*progress*(3-2*progress);for(const g of Object.values(groups)){g.position.copy(g.userData.home).addScaledVector(g.userData.offset,eased);g.quaternion.copy(g.userData.rotation);g.scale.copy(g.userData.scale)}}
 if(focusMotion){const f=focusMotion;let q=f.duration?Math.min(1,(t-f.start)/f.duration):1;let e=q*q*(3-2*q);camera.position.lerpVectors(f.from,f.to,e);controls.target.lerpVectors(f.fromTarget,f.toTarget,e);if(q===1)focusMotion=null}
 controls.update(dt);root.updateMatrixWorld();const occupied=[];for(const id of labelIds){const el=labels[id];if(progress<.85||innerWidth<700||selected){el.hidden=true;continue}groups[id].getWorldPosition(v);v.project(camera);let x=(v.x*.5+.5)*$('viewport').clientWidth,y=(-v.y*.5+.5)*$('viewport').clientHeight;let w=el.offsetWidth||100;let collide=occupied.some(r=>Math.abs(r.x-x)<(r.w+w)/2+10&&Math.abs(r.y-y)<32);el.hidden=collide||v.z>1||x<10||x+w>innerWidth||y<20||y>$('viewport').clientHeight-135;if(!el.hidden){el.style.transform=`translate(${x}px,${y}px)`;occupied.push({x,y,w})}}
 renderer.render(scene,camera);requestAnimationFrame(frame)}
$('scene').addEventListener('webglcontextlost',e=>{e.preventDefault();$('error').hidden=false});
$('progress').value=80;$('loadText').textContent='Lighting the studio';
await renderer.compileAsync(scene,camera);$('progress').value=100;requestAnimationFrame(frame);ready=true;$('loading').classList.add('done');setTimeout(()=>$('loading').hidden=true,700);
// Read-only diagnostics for regression checks; no UI dependency.
window.cameraDiagnostics=()=>({ready,language:lang,exploded,progress,selected,parts:Object.keys(groups).length,meshes:meshes.length,assembledError:Math.max(...Object.values(groups).map(g=>g.position.distanceTo(g.userData.home))),transforms:Object.fromEntries(Object.entries(groups).map(([id,g])=>[id,{position:g.position.toArray(),home:g.userData.home.toArray()}]))});
